version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydb
      ELASTICSEARCH_NODE: http://elasticsearch:9200

volumes:
  postgres_data:
  elasticsearch_data: